CREATE TABLE IF NOT EXISTS quotes (
  key TEXT NOT NULL,
  t BIGINT NOT NULL,
  v DOUBLE PRECISION NOT NULL,
  inserted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (key, t)
);

CREATE INDEX IF NOT EXISTS idx_quotes_t ON quotes (t);

